"""initial schema: 13 tabelas do LabTrack + imutabilidade do audit trail

Revision ID: 0001
Revises:
Create Date: 2026-09-24 00:01:59.820510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Audit trail append-only no nível do banco (defesa em profundidade).
AUDIT_IMMUTABLE_FUNCTION = """
CREATE OR REPLACE FUNCTION audit_logs_block_changes() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs é append-only: operação % não permitida', TG_OP
        USING ERRCODE = 'insufficient_privilege';
END;
$$ LANGUAGE plpgsql;
"""
AUDIT_IMMUTABLE_TRIGGERS = (
    "CREATE TRIGGER trg_audit_logs_no_update_delete BEFORE UPDATE OR DELETE ON audit_logs "
    "FOR EACH ROW EXECUTE FUNCTION audit_logs_block_changes()",
    "CREATE TRIGGER trg_audit_logs_no_truncate BEFORE TRUNCATE ON audit_logs "
    "FOR EACH STATEMENT EXECUTE FUNCTION audit_logs_block_changes()",
)


def _is_postgresql() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("tax_id", sa.String(length=20), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
        sa.UniqueConstraint("code", name=op.f("uq_clients_code")),
        sa.UniqueConstraint("tax_id", name=op.f("uq_clients_tax_id")),
    )
    op.create_table(
        "instruments",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("instrument_type", sa.String(length=40), nullable=False),
        sa.Column("manufacturer", sa.String(length=80), nullable=True),
        sa.Column("model", sa.String(length=80), nullable=True),
        sa.Column("serial_number", sa.String(length=80), nullable=True),
        sa.Column("location", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="ACTIVE", nullable=False),
        sa.Column("calibration_due_date", sa.Date(), nullable=True),
        sa.Column("api_key_hash", sa.String(length=255), nullable=False),
        sa.Column("last_communication_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "instrument_type IN ('PH_METER', 'HPLC', 'BALANCE', 'DENSITY_METER', 'MOISTURE_ANALYZER', 'VISCOMETER', 'THERMOMETER', 'CONDUCTIVITY_METER')",
            name=op.f("ck_instruments_instrument_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'MAINTENANCE', 'INACTIVE')",
            name=op.f("ck_instruments_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instruments")),
        sa.UniqueConstraint("code", name=op.f("uq_instruments_code")),
        sa.UniqueConstraint("serial_number", name=op.f("uq_instruments_serial_number")),
    )
    op.create_index(
        op.f("ix_instruments_instrument_type"), "instruments", ["instrument_type"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("code", name=op.f("uq_products_code")),
    )
    op.create_table(
        "roles",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "code IN ('ADMIN', 'ANALYST', 'REVIEWER', 'MANAGER')", name=op.f("ck_roles_code_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", name=op.f("uq_roles_code")),
    )
    op.create_table(
        "test_definitions",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("spec_min", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("spec_max", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("method", sa.String(length=150), nullable=False),
        sa.Column("instrument_type", sa.String(length=40), nullable=True),
        sa.Column("decimal_places", sa.SmallInteger(), server_default="2", nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "instrument_type IN ('PH_METER', 'HPLC', 'BALANCE', 'DENSITY_METER', 'MOISTURE_ANALYZER', 'VISCOMETER', 'THERMOMETER', 'CONDUCTIVITY_METER')",
            name=op.f("ck_test_definitions_instrument_type_valid"),
        ),
        sa.CheckConstraint(
            "decimal_places BETWEEN 0 AND 6", name=op.f("ck_test_definitions_decimal_places_range")
        ),
        sa.CheckConstraint(
            "spec_min IS NOT NULL OR spec_max IS NOT NULL",
            name=op.f("ck_test_definitions_spec_has_limit"),
        ),
        sa.CheckConstraint(
            "spec_min IS NULL OR spec_max IS NULL OR spec_min <= spec_max",
            name=op.f("ck_test_definitions_spec_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_definitions")),
        sa.UniqueConstraint("code", name=op.f("uq_test_definitions_code")),
    )
    op.create_table(
        "product_specifications",
        sa.Column(
            "product_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "test_definition_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("spec_min", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("spec_max", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "spec_min IS NULL OR spec_max IS NULL OR spec_min <= spec_max",
            name=op.f("ck_product_specifications_spec_range"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_specifications_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["test_definition_id"],
            ["test_definitions.id"],
            name=op.f("fk_product_specifications_test_definition_id_test_definitions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_specifications")),
        sa.UniqueConstraint(
            "product_id",
            "test_definition_id",
            name=op.f("uq_product_specifications_product_id_test_definition_id"),
        ),
    )
    op.create_index(
        op.f("ix_product_specifications_test_definition_id"),
        "product_specifications",
        ["test_definition_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_users_role_id_roles"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_index(op.f("ix_users_role_id"), "users", ["role_id"], unique=False)
    op.create_table(
        "samples",
        sa.Column("sample_code", sa.String(length=20), nullable=False),
        sa.Column(
            "product_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "client_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("lot_number", sa.String(length=50), nullable=False),
        sa.Column("origin", sa.String(length=30), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("priority", sa.String(length=10), server_default="NORMAL", nullable=False),
        sa.Column("status", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.Column(
            "responsible_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "reviewed_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_comment", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "origin IN ('PRODUCTION', 'RAW_MATERIAL', 'STABILITY', 'CUSTOMER', 'ENVIRONMENTAL')",
            name=op.f("ck_samples_origin_valid"),
        ),
        sa.CheckConstraint(
            "priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')",
            name=op.f("ck_samples_priority_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('RECEIVED', 'IN_ANALYSIS', 'AWAITING_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED')",
            name=op.f("ck_samples_status_valid"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('APPROVED', 'REJECTED') OR (reviewed_by_id IS NOT NULL AND reviewed_at IS NOT NULL)",
            name=op.f("ck_samples_reviewed_when_final"),
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_samples_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_samples_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_samples_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["responsible_id"],
            ["users.id"],
            name=op.f("fk_samples_responsible_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
            name=op.f("fk_samples_reviewed_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_samples")),
        sa.UniqueConstraint("sample_code", name=op.f("uq_samples_sample_code")),
    )
    op.create_index(op.f("ix_samples_client_id"), "samples", ["client_id"], unique=False)
    op.create_index(op.f("ix_samples_lot_number"), "samples", ["lot_number"], unique=False)
    op.create_index(op.f("ix_samples_product_id"), "samples", ["product_id"], unique=False)
    op.create_index(op.f("ix_samples_received_at"), "samples", ["received_at"], unique=False)
    op.create_index(op.f("ix_samples_responsible_id"), "samples", ["responsible_id"], unique=False)
    op.create_index(
        "ix_samples_status_received_at", "samples", ["status", "received_at"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_type", sa.String(length=12), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column(
            "instrument_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("actor_name", sa.String(length=150), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=50), nullable=False),
        sa.Column("entity_label", sa.String(length=120), nullable=True),
        sa.Column("sample_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column(
            "old_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "new_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("previous_hash", sa.CHAR(length=64), nullable=True),
        sa.Column("record_hash", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_type IN ('USER', 'INSTRUMENT', 'SYSTEM')",
            name=op.f("ck_audit_logs_actor_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_audit_logs_instrument_id_instruments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sample_id"],
            ["samples.id"],
            name=op.f("fk_audit_logs_sample_id_samples"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
        sa.UniqueConstraint("record_hash", name=op.f("uq_audit_logs_record_hash")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(
        "ix_audit_logs_entity", "audit_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_occurred_at"), "audit_logs", ["occurred_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_sample_id"), "audit_logs", ["sample_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "sample_status_history",
        sa.Column(
            "sample_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column(
            "changed_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "from_status IS NULL OR from_status IN ('RECEIVED', 'IN_ANALYSIS', 'AWAITING_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED')",
            name=op.f("ck_sample_status_history_from_status_valid"),
        ),
        sa.CheckConstraint(
            "to_status IN ('RECEIVED', 'IN_ANALYSIS', 'AWAITING_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED')",
            name=op.f("ck_sample_status_history_to_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_id"],
            ["users.id"],
            name=op.f("fk_sample_status_history_changed_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sample_id"],
            ["samples.id"],
            name=op.f("fk_sample_status_history_sample_id_samples"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sample_status_history")),
    )
    op.create_index(
        "ix_sample_status_history_sample_changed",
        "sample_status_history",
        ["sample_id", "changed_at"],
        unique=False,
    )
    op.create_table(
        "sample_tests",
        sa.Column(
            "sample_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "test_definition_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), server_default="PENDING", nullable=False),
        sa.Column("spec_min", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("spec_max", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column(
            "assigned_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'COMPLETED', 'CANCELLED')",
            name=op.f("ck_sample_tests_status_valid"),
        ),
        sa.CheckConstraint(
            "spec_min IS NULL OR spec_max IS NULL OR spec_min <= spec_max",
            name=op.f("ck_sample_tests_spec_range"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_id"],
            ["users.id"],
            name=op.f("fk_sample_tests_assigned_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sample_id"],
            ["samples.id"],
            name=op.f("fk_sample_tests_sample_id_samples"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["test_definition_id"],
            ["test_definitions.id"],
            name=op.f("fk_sample_tests_test_definition_id_test_definitions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sample_tests")),
        sa.UniqueConstraint(
            "sample_id",
            "test_definition_id",
            name=op.f("uq_sample_tests_sample_id_test_definition_id"),
        ),
    )
    op.create_index(op.f("ix_sample_tests_sample_id"), "sample_tests", ["sample_id"], unique=False)
    op.create_index(
        op.f("ix_sample_tests_test_definition_id"),
        "sample_tests",
        ["test_definition_id"],
        unique=False,
    )
    op.create_table(
        "test_results",
        sa.Column(
            "sample_test_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("value", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("spec_status", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=12), nullable=False),
        sa.Column(
            "entered_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "instrument_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "entered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "(source = 'MANUAL' AND entered_by_id IS NOT NULL) OR (source = 'INSTRUMENT' AND instrument_id IS NOT NULL)",
            name=op.f("ck_test_results_attributable"),
        ),
        sa.CheckConstraint(
            "source IN ('MANUAL', 'INSTRUMENT')", name=op.f("ck_test_results_source_valid")
        ),
        sa.CheckConstraint(
            "spec_status IN ('IN_SPEC', 'OOS')", name=op.f("ck_test_results_spec_status_valid")
        ),
        sa.CheckConstraint(
            "version = 1 OR change_reason IS NOT NULL",
            name=op.f("ck_test_results_amend_has_reason"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_test_results_version_positive")),
        sa.ForeignKeyConstraint(
            ["entered_by_id"],
            ["users.id"],
            name=op.f("fk_test_results_entered_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_test_results_instrument_id_instruments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sample_test_id"],
            ["sample_tests.id"],
            name=op.f("fk_test_results_sample_test_id_sample_tests"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_results")),
        sa.UniqueConstraint(
            "sample_test_id", "version", name=op.f("uq_test_results_sample_test_id_version")
        ),
    )
    op.create_index(
        op.f("ix_test_results_entered_at"), "test_results", ["entered_at"], unique=False
    )
    op.create_index(
        op.f("ix_test_results_entered_by_id"), "test_results", ["entered_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_test_results_instrument_id"), "test_results", ["instrument_id"], unique=False
    )
    op.create_index(
        op.f("ix_test_results_spec_status"), "test_results", ["spec_status"], unique=False
    )
    op.create_index(
        "uq_test_results_current_per_test",
        "test_results",
        ["sample_test_id"],
        unique=True,
        postgresql_where=sa.text("is_current"),
        sqlite_where=sa.text("is_current"),
    )
    op.create_table(
        "instrument_results",
        sa.Column(
            "instrument_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("sample_code", sa.String(length=20), nullable=True),
        sa.Column("test_code", sa.String(length=30), nullable=True),
        sa.Column("value", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("error_code", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "test_result_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACCEPTED', 'REJECTED')", name=op.f("ck_instrument_results_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_instrument_results_instrument_id_instruments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["test_result_id"],
            ["test_results.id"],
            name=op.f("fk_instrument_results_test_result_id_test_results"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instrument_results")),
        sa.UniqueConstraint("test_result_id", name=op.f("uq_instrument_results_test_result_id")),
    )
    op.create_index(
        "ix_instrument_results_instrument_received",
        "instrument_results",
        ["instrument_id", "received_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_instrument_results_status"), "instrument_results", ["status"], unique=False
    )
    # ### end Alembic commands ###
    if _is_postgresql():
        op.execute(AUDIT_IMMUTABLE_FUNCTION)
        for statement in AUDIT_IMMUTABLE_TRIGGERS:
            op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    if _is_postgresql():
        op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_no_truncate ON audit_logs")
        op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_no_update_delete ON audit_logs")
        op.execute("DROP FUNCTION IF EXISTS audit_logs_block_changes()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_instrument_results_status"), table_name="instrument_results")
    op.drop_index("ix_instrument_results_instrument_received", table_name="instrument_results")
    op.drop_table("instrument_results")
    op.drop_index(
        "uq_test_results_current_per_test",
        table_name="test_results",
        postgresql_where=sa.text("is_current"),
        sqlite_where=sa.text("is_current"),
    )
    op.drop_index(op.f("ix_test_results_spec_status"), table_name="test_results")
    op.drop_index(op.f("ix_test_results_instrument_id"), table_name="test_results")
    op.drop_index(op.f("ix_test_results_entered_by_id"), table_name="test_results")
    op.drop_index(op.f("ix_test_results_entered_at"), table_name="test_results")
    op.drop_table("test_results")
    op.drop_index(op.f("ix_sample_tests_test_definition_id"), table_name="sample_tests")
    op.drop_index(op.f("ix_sample_tests_sample_id"), table_name="sample_tests")
    op.drop_table("sample_tests")
    op.drop_index("ix_sample_status_history_sample_changed", table_name="sample_status_history")
    op.drop_table("sample_status_history")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_sample_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_occurred_at"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_samples_status_received_at", table_name="samples")
    op.drop_index(op.f("ix_samples_responsible_id"), table_name="samples")
    op.drop_index(op.f("ix_samples_received_at"), table_name="samples")
    op.drop_index(op.f("ix_samples_product_id"), table_name="samples")
    op.drop_index(op.f("ix_samples_lot_number"), table_name="samples")
    op.drop_index(op.f("ix_samples_client_id"), table_name="samples")
    op.drop_table("samples")
    op.drop_index(op.f("ix_users_role_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_product_specifications_test_definition_id"), table_name="product_specifications"
    )
    op.drop_table("product_specifications")
    op.drop_table("test_definitions")
    op.drop_table("roles")
    op.drop_table("products")
    op.drop_index(op.f("ix_instruments_instrument_type"), table_name="instruments")
    op.drop_table("instruments")
    op.drop_table("clients")
    # ### end Alembic commands ###
